
### guardar
POST http://127.0.0.1:8000/api/abonado
Accept: application/json
Content-Type: application/json

{
    "codigo": "4545",
    "plan": "7544857",
    "nombre": "Eduardo Andres Criollo Cabrera"
}













###
GET http://127.0.0.1:8000/api/abonado?q=CRIOLL
Accept: application/json
Content-Type: application/json


### mostrar
GET http://127.0.0.1:8000/api/actividad/4
Accept: application/json
Content-Type: application/json


### actualizar
PUT  http://127.0.0.1:8000/api/actividad/4
Accept: application/json
Content-Type: application/json

{
    "tipo": "Traslado Normal"
}

### eliminar

DELETE   http://127.0.0.1:8000/api/actividad/4
Accept: application/json
Content-Type: application/json

