POST http://127.0.0.1:8000/api/v1/auth/registrar
Accept: application/json
Content-Type: application/json


{
    "name": "Andres Criollo",
    "email": "acriollo@info.com",
    "password": "abcd1234",
    "c_password": "abcd1234"
}














### ingreso al sistema

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "andres@info.com",
    "password": "andres2013"
}